name = "Access Your Abilities"
author = "RhythmicSys"
version = "2.0.0"
description = "Modpack designed for mobility and visual accessibility"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10834ef2142d883fe30f1101bc1e56a22e3f937f39a38ddef0527eb25cd8eed8"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"

[options]
acceptable-game-versions = ["1.16.5", "1.19", "1.19.2", "1.19.3"]
